[package]
name = "fastset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanorand = "0.7.0"
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
fastrand = "1.4.0"
criterion = "0.3.4"

[[bench]]
name = "set"
path = "bench/set.rs"
harness = false